### ISSUE TITLE
je peux débuter à une date postérieur ;) à aujourd'hui

### ISSUE THREAD

**Issue by Didixe** [WildCodeSchool-2023-09/bdx-php-p3-makesense#76]
Dates à retenir
Commencée le : 2024-01-10

Prise de décision commencée

Échéance le 2024-01-11

Donner son avis

Échéance le 2024-01-12

Première décision prise

Échéance le 2024-01-13

Rentrer en conflit

Échéance le 2024-01-14

Décision définitive

**Comment by Jojopok** [comment]
C'est voulu si une décision a commencé en internet avant aujourd'hui
