### ISSUE TITLE
Create a new decision - invalid messages

### ISSUE THREAD

**Issue by Phalenopsis** [WildCodeSchool-2023-09/bdx-php-p3-makesense#78]
> Situation actuelle
> Le contexte ne doit pas être vide

> Les bénéfices
> L'avantages ne doit pas être vide

> Les risques
> Le risque ne doit pas être vide

Il n'y a pas d'uniformité singulier/pluriel, voir même pas le même mot.

**Comment by Jojopok** [comment]
Its ok now, thank you :) !
