### ISSUE TITLE
Create a new decision - invalid time messages 

### ISSUE THREAD

**Issue by Phalenopsis** [WildCodeSchool-2023-09/bdx-php-p3-makesense#81]
> La décision commencera le : 
> 29/01/2024
> Date pour donner son opinion :
> La date limite de l'avis doit être antérieure à la date de début.
> 
> 22/01/2024
> La première décision devra être prise avant le :
> La date limite de la décision doit être antérieure à la date limite de l'avis.
> 
> 15/01/2024
> Date final pour rentrer en conflit :
> La date limite du conflit doit être antérieure à la date limite de la décision.
> 
> 08/01/2024
> La décision devra être prise avant le :
> La date limite finale doit être antérieure à la date limite du conflit.

on retrouve le manque d'uniformité du nommage. 

>la date limite doit  être antérieure

cela veut dire qu'elle doit être avant. ce qui n'est pas ce que vous vouliez dire

**Comment by Jojopok** [comment]
its ok now :), thank you =D !
