### ISSUE TITLE
dans créer une décision

### ISSUE THREAD

**Issue by Didixe** [WildCodeSchool-2023-09/bdx-php-p3-makesense#83]
Choix des groupes dans créer une décision
le champ est plus long que les 2 autres

**Comment by Didixe** [comment]
aligner le bouton Envoyer ma décision ?

**Comment by Virosa** [comment]
alors pour le input choix des groupes, sur mon mac, il est aussi grand que les 2 autres, mais sur celui de Sami en effet, il y a une légère différence. Je ne peux donc pas faire cette rectif, car je n'ai pas la vue qu'il faut. Je te laisse la main dessus, Jonathan !

**Comment by Virosa** [comment]
et aussi changer le mot "opinion" avec "avis" dans : Date pour donner son **opinion :**

**Comment by Jojopok** [comment]
its ok now :), thank you =D !
