### ISSUE TITLE
lambda

### ISSUE THREAD

**Issue by Didixe** [WildCodeSchool-2023-09/bdx-php-p3-makesense#88]
c vicky,
page co:
 souligné "mot de passe oublié" pour que l'user comprenne qu'il y a un lien.

navbar:
ça serait top; quand le curseur passe sur un des boutons de la nav, que ça change de couleur

bref, voila trop bien votre projet, vous avez assuré, gros bisous

**Comment by Jojopok** [comment]
Super idée merci :) !
